elo7/tech-blog

src/layouts/page.html.hb

Ajustando o link do footer, estava tech.elo7.com.br :)

Fix no link do footer

---

README.md

Revisão do README

---

src/posts/desmistificando-dagger2.html.md

🔨  @rsicarelli
Explorando o framework de Inversão de Dependência, Dagger 2;

[android_dagger2] - Desmistificando o Dagger 2

---

src/layouts/page.html.hb

👍  @FernandaBernardo 
@rapahaeru

Adiciona metadata para copyright no footer

---

.gitignore
src/assets/_markdown.scss
src/assets/main.css.scss

👍  @tcelestino
Pequeno fix de layout na tag code do markdown. Mudei a fonte, e adicionei um espaçamento maior. Além disso, adicionei css para o itálico no markdown.

Fix layout: code markdown

---

README.md

👍 @FernandaBernardo
Tive dúvida sobre como referenciar uma imagem no meu post, então pensei em adicionar essa informação ao README
@luiz

Adicionando endereço em que as imagens são servidas ao README

---

docpad.js
src/layouts/page.html.hb

👁  @tcelestino
Closes #26 
@fernandabernardo

Adiciona google analytics

---

src/posts/introducao-a-programacao-funcional-com-java8.html.md
src/posts/java8-o-que-mudou.html.md

[POST] Introdução à programação funcional com Java 8

---

src/posts/vagas-estagio.html.md

@fernandabernardo @davidrobert

[POST] Vagas estágio

---

src/layouts/page.html.hb

Adiciona meta tag do google search console

---

src/posts/introducao-ao-java-2.html.md

👍   @fernandabernardo
Segundo post sobre Introdução ao Java, abordando expressões booleanas e controle de loops.
@tcelestino

[POST] Introdução ao Java - parte 2

---

src/posts/wai-aria-apanhado-geral.html.md

[POST] 1/3: Um apanhado geral sobre o WAI-ARIA

---

src/posts/wai-aria-roles.html.md

[POST] 2/3: Os papéis do WAI-ARIA no HTML

---

src/public/robots.txt
src/public/sitemap.xml

👍  @AlineLee @tcelestino
⚠️  Quando mergear precisa adicionar o sitemap no https://www.google.com/webmasters/tools/sitemap-list

Adiciona robots.txt e sitemap

---

docpad.js
src/assets/js/analytics.js
src/assets/js/vendor/ajax.js
src/assets/js/vendor/async-define.js
src/assets/js/vendor/doc.js
src/assets/js/vendor/events-amd.js
src/layouts/page.html.hb

👍   @luiz
@FernandaBernardo 
👀   Já está adicionado no GA de dev
⚠️  Precisa adicionar as custom dimensions e metrics no Google Analytics de Prod
* CLIENT_ID - custom dimension - scope "User" - dimension1
Metrics - scope "Hit" - formatting type "Integer":
* RESPONSE_END_TIME - metric1
* DOM_LOAD_TIME - metric2
* WINDOW_LOAD_TIME - metric3
Referência: https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/

Adiciona novas métricas para o GA

---

README.md
deploy-enhancement.sh
deploy-post.sh
deploy.sh

👍   @alineLee
@fernandabernardo @luiz 
🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 
🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

Script deploy

---

docpad.js
package.json

Atualiza versões das libs

---

docpad.js

[fix-share] Fix url do blog

---

src/layouts/page.html.hb

[fix-opengraph-url] Corrige URL nas meta-tags do OpenGraph

---

package.json
src/posts/vagas-data-scientist.html.md

[POST] Vaga Data Scientist

---

src/posts/google-io.html.md

fixes de português

---

src/layouts/page.html.hb

@FernandaBernardo pode verificar se faz sentido seguirmos assim!? ;-)

adicionado barra ao final das urls das categorias para evitar redirect

---

src/posts/wai-aria-states-properties.html.md

[POST] 3/3: Os estados e propriedades das roles no WAI-ARIA

---

src/posts/vagas-search.html.md

[POST] Vagas para search

---

src/posts/vagas-mobile.html.md

[POST] Vagas mobile

---

src/posts/html-semantico-1.html.md
src/posts/html-semantico-2.html.md

[fix-posts-semantica] Adiciona link faltante do primeiro post

---

README.md
src/publishers/fernandabernardo.html.md

[fix-readme] Atualiza README

---

src/publishers/tcelestino.html.md

👍 @fernandabernardo
Adicionei a descrição para o meu perfil. 🏖

Adiciona descrição do perfil Tiago Celestino

---

src/documents/back-end.html.hb
src/documents/devops.html.hb
src/documents/eventos.html.hb
src/documents/front-end.html.hb
src/documents/index.html.hb
src/documents/mobile.html.hb
src/documents/vagas.html.hb
src/posts/vagas-data-scientist.html.md
src/posts/vagas-devops-post.html.md
src/posts/vagas-java-post.html.md
src/posts/vagas-mobile.html.md
src/posts/vagas-search.html.md

👍  @tiagolimaelo7 
@alinelee
Corrige descriptions que estão marcadas pelo search console para serem melhoradas.
https://www.google.com/webmasters/tools/html-suggestions?hl=pt-BR&siteUrl=http://engenharia.elo7.com.br/

[fix-meta-description] Corrige descriptions

---

src/posts/vagas-devops.html.md
src/posts/vagas-devops.mdown
src/publishers/jlmfonseca.html.md

Adiciona vaga Devops para o Beyond

---

src/posts/microservicos-rest.html.md
src/posts/testes-codigo-mockito.html.md

@tiagolimaelo7 😅
Corrige o autor dos posts de minha autoria para @ljtfreitas (meu Github pessoal, que não utilizo aqui)

[fix-tiagolimaelo7-author] Corrige nome do autor Tiago Lima

---

src/posts/css-basics-display.html.md

👍  @leonardosouza 
@fernandabernardo

[POST] CSS Basics - Display

---

src/assets/posts.css.scss

👍  @tcelestino
@fernandabernardo

[fix-dot-author] Ajuste de layout

---

src/posts/terraformando-tudo-2.html.md
src/publishers/lucasvasconcelos.html.md

@lucasvasconcelos 
👍  @tiagolimaelo7

[POST] Terraformando Tudo - Parte 02

---

src/layouts/page.html.hb

[fix-async-define] Fix carregamento async define

---

docpad.js
package.json
src/assets/_colors.scss
src/assets/main.css.scss
src/assets/posts.css.scss
src/documents/back-end.html.hb
src/documents/devops.html.hb
src/documents/eventos.html.hb
src/documents/front-end.html.hb
src/documents/index.html.hb
src/documents/mobile.html.hb
src/documents/vagas.html.hb
src/layouts/page.html.hb
src/layouts/publisher.html.hb

[pagination] Adiciona paginação para os posts

---

src/documents/home.html.hb
src/documents/index.html.hb
src/layouts/category-template-amp.html.hb
src/layouts/category-template.html.hb
src/layouts/page-amp.html.hb
src/layouts/page.html.hb
src/layouts/post-amp.html.hb
src/layouts/post.html.hb
src/layouts/publisher-amp.html.hb
src/layouts/publisher.html.hb
src/layouts/tags.html.hb

👍  @tisvasconcelos 
Evita os redirects do blog causados por url sem barra no final.
@erikatakahara @leonardosouza

[fix-redirect-url] Corrige redirects do blog

---

src/posts/terraformando-tudo-3.html.md
src/publishers/lucasvasconcelos.html.md

[POST] - Terraformando tudo 03

---

.gitignore

👍  @leonardosouza
👷‍♀️ @FernandaBernardo

Adiciona package-lock no gitignore

---

.travis.yml
src/posts/customizando-campos-de-formulario-com-elo7-mask-amd.html.md
src/posts/frameworks-js.html.md

👍  @FernandaBernardo 
@luiz @williammizuta

Criando referencias ciclicas

---

package.json

👍  @leonardosouza
@williammizuta
:hammer: Fixes: 0

[update-libs] Atualiação de bibliotecas

---

src/posts/minimizando-codigo-duplicado-com-react-native.html.md

@aterribili 
Review português: @lucasvasconcelos

[POST] Minimizando código duplicado com React Native no Elo7

---

src/publishers/macadantas.html.md

Inclui biografia da Camila Tessarolo

---

src/posts/otimizacao-de-busca-em-faixas-de-valores.html.md

Remove especificação de linguagem CSV de bloco de código para não dar warning no build do blog

---

src/posts/otimizacao-de-busca-em-faixas-de-valores.html.md

👍 @luiz
@tiagolimaelo7
- Corrige erro de digitação no post "Otimização de busca em faixas de valores"

[fix-procura-faixa-cep] Corrige erro de digitação no post "Otimização de busca em faixas de valores"

---

src/posts/novidades-do-junit-5-parte-1.html.md

@tiagolimaelo7
- Remove markdown da descricao do post sobre Junit 5

[fix-junit-5-description] Remove markdown da descricao do post sobre Junit 5

---

docpad.js
src/assets/main.css.scss
src/documents/home.html.hb
src/documents/index.html.hb
src/layouts/category-template.html.hb
src/layouts/page.html.hb

Ajustes para melhorar a acessibilidade no blog

---

docpad.js
package.json

@erikatakahara
Para testar utilize o comando "npm run fast-dev"

Otimiza desenvolvimento local

---

src/posts/novidades-do-junit-5-parte-2.html.md

👍 @tisvasconcelos
@tiagolimaelo7

[POST] - Novidades do JUnit 5 - parte 2

---

src/posts/vagas-data-scientist-cientista-de-dados.html.md
src/posts/vagas-data-scientist.html.md

@FernandaBernardo 
👍  @tiagolimaelo7 @luiz

[POST] Vagas Data Scientist

---

docpad.js
src/layouts/page.html.hb
src/layouts/post.html.hb

[tags-lowercase] Adiciona helper e transformar qualquer tag em lower case

---

src/posts/a-cultura-por-tras-do-time-fora-de-serie.html.md

Me reportaram que essa letrinha acabou escapando e subindo pra prod :/
@leonardosouza

fix letra `f` que escapou

---

src/posts/vagas-search-2017-12.html.md

[POST] Vaga de search developer

---

src/posts/retrospectiva-front-end-2017.html.md

Fix - retrospectiva front end

---

src/posts/vaga-data-engineer.html.md
src/publishers/davidrobert.html.md

Cria post para a nova vaga de Data Engineer

---

src/posts/subindo-uma-api-rest-em-clojure.html.md

[POST] Subindo uma API REST em Clojure

---

src/documents/data-science.html.hb
src/json/categories.json
src/layouts/page.html.hb
src/posts/convolucao.html.md

- Adiciona categoria "Data Science" no blog.
- Atualiza categoria do post "Princípios de Processamento de Imagens: Uma introdução à Convolução".
@williammizuta

Adiciona categoria "Data Science"

---

src/posts/novidades-do-junit-5-parte-1.html.md

Para corrigir:
```shell
Error: Highlight.js: Syntax highlight definition does not exist for language: csv
Your probably want to add an alias for this language to one that we do support
More information here: https://github.com/docpad/docpad-plugin-highlightjs#language-aliases
at DocPad.warn (/home/travis/build/elo7/tech-blog/node_modules/docpad/out/lib/docpad.js:3541:50)
at HighlightjsPlugin.highlightSource (/home/travis/build/elo7/tech-blog/node_modules/docpad-plugin-highlightjs/es5/highlightjs.plugin.js:91:22)
at replace (/home/travis/build/elo7/tech-blog/node_modules/docpad-plugin-highlightjs/es5/highlightjs.plugin.js:140:31)
at Task.<anonymous> (/home/travis/build/elo7/tech-blog/node_modules/docpad-plugin-highlightjs/node_modules/bal-util/out/lib/html.js:73:20)
at …
```

[fix-highlightjs] Remove highlightjs code que não é aceito

---

src/posts/otimizacao-bd.html.md
src/publishers/victorkendy.html.md

👍 @fernandabernardo
@victorkendy

[POST] Otimizacao bd

---

src/posts/otimizacao-bd.html.md

fix de acento em tag

---

src/posts/programacao-reativa.html.md

Pequenos fixes Programação Reativa

---

src/layouts/page.html.hb

👍 @tcelestino
@fernandabernardo

[latex-support] Adiciona script para suporte a latex

---

src/posts/conheca-o-dustjs.html.md

Primeira parte do post sobre o Dust.js. 
@tcelestino

[POST] Conhecendo o Dust.js, framework javascript isomórfico

---

src/posts/vagas-desenvolverdor-mobile.html.md
src/publishers/tisvasconcelos.html.md

[vaga-mobile] Página com vaga no time de mobile

---

src/posts/boas-praticas-na-utilizacao-k8s.html.md
src/publishers/marcusrios.html.md

👍 @tiagolimaelo7 
Boas práticas na utilização do Kubernetes em produção

[POST] Good practices k8s

---

src/posts/conheca-o-dustjs.html.md

Fiz uma pequena melhoria no texto relacionado ao uso do verbo "estão" e "estejam". Podem avaliar?

Correção texto

---

src/assets/post.css.scss
src/posts/techtalk-jogos-indo-alem-do-simples-css.html.md

@FernandaBernardo 
👍 @tiagolimaelo7

Techtalk - Jogos: indo além do simples CSS

---

src/assets/posts.css.scss
src/assets/publisher.css.scss
src/layouts/publisher.html.hb

@FernandaBernardo 
👍 @tiagolimaelo7

[fix-card] Corrige layout da página do autor

---

src/posts/design-e-entregabilidade-de-emails.html.md
src/publishers/kkstv.html.md

🖊 @kkstv
👍 @tiagolimaelo7 
- Post sobre entregabilidade de emails e design

[POST] Design e entregabilidade de emails

---

src/documents/talks/criando-times-de-alto-desempenho.html.md
src/documents/talks/experiencia-do-usuario-no-mundo-web.html.md
src/documents/talks/incorporando-acessibilidade-no-seu-projeto.html.md
src/documents/talks/introducao-ao-kotlin.html.md
src/documents/talks/perceived-performance.html.md

👍 @williammizuta @luiz @davidrobert 

[novas-palestras] Adiciona novas palestras

---

src/publishers/fernandabernardo.html.md

[fix-fernanda] Atualiza rede social

---

content/posts/caracteristicas-do-big-data.md
content/posts/convolucao.md
content/posts/elo7-analytics-elytics.md
content/posts/flink-spark.md
content/posts/google-io.md
content/posts/nightfall.md
content/posts/otimizacao-de-busca-em-faixas-de-valores.md

[ajuste-categorias] Categorias Big Data e Machine Learning

---

layouts/partials/date.html
layouts/posts/single.html

[meta-for-search] Adiciona meta para busca

---

layouts/partials/footer.html

[fix-math-jax] Fix do math jax

---

layouts/partials/head.html

[fix-twitter-image] Fix twitter image open graph

---

layouts/partials/head.html

Adiciona verification do google console

---

layouts/authors/single.html
layouts/category/category.html
layouts/posts/single.html
layouts/section/meetups.html
layouts/section/talks.html
layouts/tag/tag.html
layouts/talks/single.html

[fix-analytics] Fix para enviar dados para GA

---

content/posts/programacao-reativa-parte-2.md
content/posts/programacao-reativa-parte-3.md
content/posts/programacao-reativa-parte-4.md
content/posts/programacao-reativa-parte-5.html.md
content/posts/programacao-reativa-parte-5.md
content/posts/programacao-reativa.md

🖊 @tiagolimaelo7 
Programação Reativa - Parte 5

[POST] Programação Reativa - Parte 5

---

content/authors/davidrobert.md
static/css/publisher.scss

👍  @FernandaBernardo 
@erikatakahara

Corrige descrição do author davidrobert

---

layouts/posts/single.html

[hackday-meta-category] Inclui categoria para permitir a indexação dos posts para busca

---

content/posts/airflow-spark.md

@sardinha :heart: 
Descreve a execução do spark no kubernetes + airflow

Post airflow + spark

---

content/posts/jupyter-enterprise-gateway.md

:hammer: @sardinha 
- Corrige bullets das listas

[HD-204-fix-bullets] Corrige bullets
